[features]
seeds = false
skip-lint = false
[programs.localnet]
mysolanaapp = "2vVWw8NNrze47tiDGUsJvBsCMnZSeJordt5kGzhvRUBi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/pnkhoodie/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
